name: zonex_app
description: "ZonEx Flutter project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.5
  flutter_blue_plus: ^2.3.13
  intl: ^0.20.3
  sqflite: ^2.4.4
  health: ^13.3.2
  flutter_tts: ^4.2.5
  path: ^1.9.1
  just_audio: ^0.10.6
  get_it: ^9.3.0
  wakelock_plus: ^1.8.0
  permission_handler: 11.3.1 # Зафиксировали более раннюю версию
  typed_data: ^1.4.0
  bloc_concurrency: ^0.3.0
  rxdart: ^0.28.0
  freezed: ^4.0.2
  freezed_annotation: ^3.1.0
  flutter_foreground_task: ^11.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  # ДОБАВЛЕНО: Инструменты генерации кода
  build_runner: ^2.4.15



# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/audio/start.mp3
    - assets/audio/pause.mp3
    - assets/audio/resume.mp3
    - assets/audio/stop.mp3

